apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: gateway-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: ct-staging-static-ip
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "gce"
spec:
  tls:
  - hosts:
    - staging-api.globalforestwatch.org
    - staging.emissionspathways.org
    - ui-staging.resourcewatch.org
    secretName: ct-staging-tls
  rules:
  - host: staging-api.globalforestwatch.org
    http:
      paths:
      - path: /*
        backend:
          serviceName: nginx
          servicePort: 80
  - host: staging.emissionspathways.org
    http:
      paths:
      - path: /*
        backend:
          serviceName: nginx
          servicePort: 80
  - host: ui-staging.resourcewatch.org
    http:
      paths:
      - path: /*
        backend:
          serviceName: ct-ui
          servicePort: 80
