apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: gateway-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: ct-static-ip
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "gce"
spec:
  tls:
  - hosts:
    - rw-blog.vizzuality.com
    - api-rw.vizzuality.com
    - climate-watch.vizzuality.com
    - resourcewatch.vizzuality.com
    - ui.resourcewatch.org
    - api.resourcewatch.org
    - staging.resourcewatch.org
    - production-api.globalforestwatch.org
    - emissionspathways.org
    - www.emissionspathways.org
    - climatewatchdata.org
    - www.climatewatchdata.org
    - beta.climatewatchdata.org
    - resourcewatch.vizzuality.com
    - staging.prepdata.org
    - beta.prepdata.org
    - www.prepdata.org
    - prepdata.org
    - preproduction.prepdata.org
    - climatedata.org
    - www.climatedata.org
    - data.emissionspathways.org
    secretName: ct-prod-tls
  rules:
  - host: staging.prepdata.org
    http:
      paths:
      - path: /*
        backend:
          serviceName: nginx
          servicePort: 80
  - host: beta.prepdata.org
    http:
      paths:
      - path: /*
        backend:
          serviceName: nginx
          servicePort: 80
  - host: www.prepdata.org
    http:
      paths:
      - path: /*
        backend:
          serviceName: nginx
          servicePort: 80
  - host: prepdata.org
    http:
      paths:
      - path: /*
        backend:
          serviceName: nginx
          servicePort: 80
  - host: preproduction.prepdata.org
    http:
      paths:
      - path: /*
        backend:
          serviceName: nginx
          servicePort: 80
  - host: rw-blog.vizzuality.com
    http:
      paths:
      - path: /*
        backend:
          serviceName: nginx
          servicePort: 80
  - host: api-rw.vizzuality.com
    http:
      paths:
      - path: /*
        backend:
          serviceName: nginx
          servicePort: 80
  - host: climate-watch.vizzuality.com
    http:
      paths:
      - path: /*
        backend:
          serviceName: nginx
          servicePort: 80
  - host: resourcewatch.vizzuality.com
    http:
      paths:
      - path: /*
        backend:
          serviceName: nginx
          servicePort: 80
  - host: ui.resourcewatch.org
    http:
      paths:
      - path: /*
        backend:
          serviceName: ct-ui
          servicePort: 80
  - host: api.resourcewatch.org
    http:
      paths:
      - path: /*
        backend:
          serviceName: nginx
          servicePort: 80
  - host: staging.resourcewatch.org
    http:
      paths:
      - path: /*
        backend:
          serviceName: nginx
          servicePort: 80
  - host: production-api.globalforestwatch.org
    http:
      paths:
      - path: /*
        backend:
          serviceName: nginx
          servicePort: 80
  - host: emissionspathways.org
    http:
      paths:
      - path: /*
        backend:
          serviceName: nginx
          servicePort: 80
  - host: www.emissionspathways.org
    http:
      paths:
      - path: /*
        backend:
          serviceName: nginx
          servicePort: 80
  - host: climatewatchdata.org
    http:
      paths:
      - path: /*
        backend:
          serviceName: nginx
          servicePort: 80
  - host: resourcewatch.vizzuality.com
    http:
      paths:
      - path: /*
        backend:
          serviceName: nginx
          servicePort: 80
  - host: climate-watch.vizzuality.com
    http:
      paths:
      - path: /*
        backend:
          serviceName: nginx
          servicePort: 80
  - host: www.climatewatchdata.org
    http:
      paths:
      - path: /*
        backend:
          serviceName: nginx
          servicePort: 80
  - host: climatedata.org
    http:
      paths:
      - path: /*
        backend:
          serviceName: nginx
          servicePort: 80
  - host: www.climatedata.org
    http:
      paths:
      - path: /*
        backend:
          serviceName: nginx
          servicePort: 80
  - host: beta.climatewatchdata.org
    http:
      paths:
      - path: /*
        backend:
          serviceName: nginx
          servicePort: 80
  - host: data.emissionspathways.org
    http:
      paths:
      - path: /*
        backend:
          serviceName: nginx
          servicePort: 80
